/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */
package Parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 49;
  /** RegularExpression Id. */
  int STRING = 50;
  /** RegularExpression Id. */
  int ID = 51;
  /** RegularExpression Id. */
  int LETTER = 52;
  /** RegularExpression Id. */
  int DIGIT = 53;
  /** RegularExpression Id. */
  int UNDER = 54;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"null\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"void\"",
    "\"int\"",
    "\"boolean\"",
    "\".\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"main\"",
    "\"String\"",
    "\"Thread\"",
    "\"Xinu\"",
    "\"new\"",
    "\"extends\"",
    "\"synchronized\"",
    "\"return\"",
    "<INT>",
    "<STRING>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\"_\"",
    "<token of kind 55>",
    "\"!=\"",
  };

}
