/* MiniJavaParser.java */
/* Generated By:JavaCC: Do not edit this line. MiniJavaParser.java */
  package Parse;
  import java.util.LinkedList;
  public class MiniJavaParser implements MiniJavaParserConstants {

/********************/
/* MiniJava Grammar */
/********************/

// Goal 	::= 	MainClass ( ClassDeclaration | ThreadDeclaration )* <EOF>
  static final public Absyn.Program Goal() throws ParseException {LinkedList<Absyn.ClassDecl> cl = new LinkedList<Absyn.ClassDecl>();
    MainClassDeclaration(cl);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 8:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      if (jj_2_1(2147483647)) {
        ThreadDeclaration(cl);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 8:{
          ClassDeclaration(cl);
          break;
          }
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    jj_consume_token(0);
{if ("" != null) return new Absyn.Program(cl);}
    throw new Error("Missing return statement in function");
}

// MainClass 	::= 	"class" Identifier "{" "public" "static" "void" "main" "(" "String" "[" "]" Identifier ")" "{" Statement "}" "}"
  static final public Absyn.ClassDecl MainClassDeclaration(LinkedList<Absyn.ClassDecl> cl) throws ParseException {Absyn.ClassDecl  cd;
 Absyn.Stmt stmt;
 Absyn.VarDecl var;
 Token name, arg;
 LinkedList<Absyn.MethodDecl> methods = new LinkedList<Absyn.MethodDecl>();
 LinkedList<Absyn.Formal> formals     = new LinkedList<Absyn.Formal>();
 LinkedList<Absyn.VarDecl> locals     = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.Stmt> stmts         = new LinkedList<Absyn.Stmt>();
    jj_consume_token(8);
    name = jj_consume_token(ID);
    jj_consume_token(33);
    jj_consume_token(9);
    jj_consume_token(10);
    jj_consume_token(18);
    jj_consume_token(41);
    jj_consume_token(35);
    jj_consume_token(42);
    jj_consume_token(37);
    jj_consume_token(38);
    arg = jj_consume_token(ID);
    jj_consume_token(36);
formals.add(new Absyn.Formal(
   new Absyn.ArrayType(
    new Absyn.IdentifierType("String")),
     arg.toString()));
    jj_consume_token(33);
    label_2:
    while (true) {
      if (jj_2_2(2147483647)) {
        ;
      } else {
        break label_2;
      }
      var = VarDeclaration();
locals.add(var);
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 11:
      case 12:
      case 13:
      case 14:
      case 15:
      case 16:
      case 24:
      case 32:
      case 33:
      case 35:
      case 44:
      case 45:
      case INT:
      case STRING:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_3;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(34);
    jj_consume_token(34);
methods.add(new Absyn.MethodDecl(null, false, "main", formals,
    locals, stmts, new Absyn.IntegerLiteral(0)));
  cd = new Absyn.ClassDecl(name.toString(),
      null,
      new LinkedList<Absyn.VarDecl>(), methods);
  cl.add(cd);
  {if ("" != null) return cd;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.ClassDecl ClassDeclaration(LinkedList<Absyn.ClassDecl> cl) throws ParseException {Absyn.ClassDecl  cd;
 Absyn.Stmt stmt;
 Absyn.MethodDecl var;
 Absyn.VarDecl var2;
 Token name,arg;
 Token name2 = null;
 LinkedList<Absyn.MethodDecl> methods = new LinkedList<Absyn.MethodDecl>();
 LinkedList<Absyn.VarDecl> fields = new LinkedList<Absyn.VarDecl>();
    jj_consume_token(8);
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 46:{
      jj_consume_token(46);
      name2 = jj_consume_token(ID);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    jj_consume_token(33);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 9:
      case 19:
      case 20:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 19:
      case 20:
      case ID:{
        var2 = FieldDeclaration();
fields.add(var2);
        break;
        }
      case 9:{
        var = MethodDeclaration();
methods.add(var);
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(34);
cd = new Absyn.ClassDecl(name.toString(),
      (name2 == null)? null : name2.toString(),
      fields, methods);
  cl.add(cd);
  {if ("" != null) return cd;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.ThreadDecl ThreadDeclaration(LinkedList<Absyn.ClassDecl> cl) throws ParseException {Absyn.ThreadDecl  cd;
 Absyn.MethodDecl var;
 Token name;
 LinkedList<Absyn.MethodDecl> methods = new LinkedList<Absyn.MethodDecl>();
 LinkedList<Absyn.VarDecl> locals = new LinkedList<Absyn.VarDecl>();
 Absyn.VarDecl var2;
    jj_consume_token(8);
    name = jj_consume_token(ID);
    jj_consume_token(46);
    jj_consume_token(43);
    jj_consume_token(33);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 9:
      case 19:
      case 20:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        break label_5;
      }
      if (jj_2_3(2147483647)) {
        var2 = FieldDeclaration();
locals.add(var2);
      } else if (jj_2_4(2)) {
        var = MethodDeclaration();
methods.add(var);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 9:{
          var = VoidDeclaration();
methods.add(var);
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    jj_consume_token(34);
cd = new Absyn.ThreadDecl(name.toString(),"Thread",locals, methods);
  cl.add(cd);
  {if ("" != null) return cd;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.MethodDecl MethodDeclaration() throws ParseException {boolean synced = false;
 Absyn.Type type, argsType;
 Absyn.Stmt stmt;
 Absyn.VarDecl var;
 Token name, arg;
 LinkedList<Absyn.Formal> formals     = new LinkedList<Absyn.Formal>();
 LinkedList<Absyn.VarDecl> locals     = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.Stmt> stmts         = new LinkedList<Absyn.Stmt>();
 Absyn.Expr e1;
 Absyn.Formal formal;
    jj_consume_token(9);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 47:{
      jj_consume_token(47);
synced = true;
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    type = Type();
    name = jj_consume_token(ID);
    jj_consume_token(35);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 19:
    case 20:
    case ID:{
      argsType = Type();
      arg = jj_consume_token(ID);
formal = new Absyn.Formal(argsType, arg.toString()); formals.add(formal);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 40:{
          ;
          break;
          }
        default:
          jj_la1[9] = jj_gen;
          break label_6;
        }
        jj_consume_token(40);
        argsType = Type();
        arg = jj_consume_token(ID);
formal = new Absyn.Formal(argsType, arg.toString()); formals.add(formal);
      }
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    jj_consume_token(36);
    jj_consume_token(33);
    label_7:
    while (true) {
      if (jj_2_5(2147483647)) {
        ;
      } else {
        break label_7;
      }
      var = VarDeclaration();
locals.add(var);
    }
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 11:
      case 12:
      case 13:
      case 14:
      case 15:
      case 16:
      case 24:
      case 32:
      case 33:
      case 35:
      case 44:
      case 45:
      case INT:
      case STRING:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_8;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(48);
    e1 = Expression();
    jj_consume_token(39);
    jj_consume_token(34);
{if ("" != null) return new Absyn.MethodDecl(type,synced,name.toString(),formals,locals,stmts,e1);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.VarDecl FieldDeclaration() throws ParseException {Absyn.Type type;
 Token name;
    type = Type();
    name = jj_consume_token(ID);
    jj_consume_token(39);
{if ("" != null) return new Absyn.VarDecl(type,name.toString(),null);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.VoidDecl VoidDeclaration() throws ParseException {Absyn.Stmt stmt;
 Token name;
 Absyn.VarDecl var;
 LinkedList<Absyn.VarDecl> locals     = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.Stmt> stmts         = new LinkedList<Absyn.Stmt>();
    jj_consume_token(9);
    jj_consume_token(18);
    name = jj_consume_token(ID);
    jj_consume_token(35);
    jj_consume_token(36);
    jj_consume_token(33);
    label_9:
    while (true) {
      if (jj_2_6(2147483647)) {
        ;
      } else {
        break label_9;
      }
      var = VarDeclaration();
locals.add(var);
    }
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 11:
      case 12:
      case 13:
      case 14:
      case 15:
      case 16:
      case 24:
      case 32:
      case 33:
      case 35:
      case 44:
      case 45:
      case INT:
      case STRING:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_10;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(34);
{if ("" != null) return new Absyn.VoidDecl(null,false,name.toString(),null,locals,stmts,null);}
    throw new Error("Missing return statement in function");
}

//MethodDeclaration	::=	"public" ( "synchronized" )? 
//Type <ID> "(" ( Type <ID> ( "," Type <ID> )* )? ")" "{" ( VarDeclaration )* ( Statement )* "return" Expression ";" "}" 

// VarDeclaration 	::= 	Type Identifier ( = Expression )? ";"
  static final public Absyn.VarDecl VarDeclaration() throws ParseException {Absyn.Type type = null;
 Token      name = null;
 Absyn.Expr init = null;
    type = Type();
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 22:{
      jj_consume_token(22);
      init = Expression();
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
    jj_consume_token(39);
{if ("" != null) return new Absyn.VarDecl(type, name.toString(), init);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Type Type() throws ParseException {Absyn.Type type;
    type = BaseType();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 37:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_11;
      }
      jj_consume_token(37);
      jj_consume_token(38);
type = new Absyn.ArrayType(type);
    }
{if ("" != null) return type;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Type BaseType() throws ParseException {Token name;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 20:{
      name = jj_consume_token(20);
{if ("" != null) return new Absyn.BooleanType();}
      break;
      }
    case 19:{
      name = jj_consume_token(19);
{if ("" != null) return new Absyn.IntegerType();}
      break;
      }
    case ID:{
      name = jj_consume_token(ID);
{if ("" != null) return new Absyn.IdentifierType(name.toString());}
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Stmt Statement() throws ParseException {Absyn.Stmt stmt;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 33:{
      stmt = BlockCallStatement();
{if ("" != null) return stmt;}
      break;
      }
    case 44:{
      stmt = XinuCallStatement();
{if ("" != null) return stmt;}
      break;
      }
    case 15:{
      stmt = WhileCallStatement();
{if ("" != null) return stmt;}
      break;
      }
    case 16:{
      stmt = IfCallStatement();
{if ("" != null) return stmt;}
      break;
      }
    case 11:
    case 12:
    case 13:
    case 14:
    case 24:
    case 32:
    case 35:
    case 45:
    case INT:
    case STRING:
    case ID:{
      stmt = AssignCallStatement();
{if ("" != null) return stmt;}
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.AssignStmt AssignCallStatement() throws ParseException {Absyn.Expr arg1, arg2;
    arg1 = Expression();
    jj_consume_token(22);
    arg2 = Expression();
    jj_consume_token(39);
{if ("" != null) return new Absyn.AssignStmt((Absyn.AssignableExpr)arg1, arg2);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.BlockStmt BlockCallStatement() throws ParseException {Absyn.Stmt stmt;
 LinkedList<Absyn.Stmt> stmts = new LinkedList<Absyn.Stmt>();
    jj_consume_token(33);
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 11:
      case 12:
      case 13:
      case 14:
      case 15:
      case 16:
      case 24:
      case 32:
      case 33:
      case 35:
      case 44:
      case 45:
      case INT:
      case STRING:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_12;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(34);
{if ("" != null) return new Absyn.BlockStmt(stmts);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.IfStmt IfCallStatement() throws ParseException {Absyn.Expr test;
 Absyn.Stmt thenStm;
 Absyn.Stmt elseStm = null;
    jj_consume_token(16);
    jj_consume_token(35);
    test = Expression();
    jj_consume_token(36);
    thenStm = Statement();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 17:{
      jj_consume_token(17);
      elseStm = Statement();
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      ;
    }
{if ("" != null) return new Absyn.IfStmt(test, thenStm, elseStm);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.WhileStmt WhileCallStatement() throws ParseException {Absyn.Expr test;
 Absyn.Stmt body;
    jj_consume_token(15);
    jj_consume_token(35);
    test = Expression();
    jj_consume_token(36);
    body = Statement();
{if ("" != null) return new Absyn.WhileStmt(test, body);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.XinuCallStmt XinuCallStatement() throws ParseException {Token method;
 Absyn.Expr arg;
 LinkedList<Absyn.Expr> args = new LinkedList<Absyn.Expr>();
    jj_consume_token(44);
    jj_consume_token(21);
    method = jj_consume_token(ID);
    jj_consume_token(35);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 11:
    case 12:
    case 13:
    case 14:
    case 24:
    case 32:
    case 35:
    case 44:
    case 45:
    case INT:
    case STRING:
    case ID:{
      arg = Expression();
args.add(arg);
      label_13:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 40:{
          ;
          break;
          }
        default:
          jj_la1[19] = jj_gen;
          break label_13;
        }
        jj_consume_token(40);
        arg = Expression();
args.add(arg);
      }
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      ;
    }
    jj_consume_token(36);
    jj_consume_token(39);
{if ("" != null) return new Absyn.XinuCallStmt(method.toString(), args);}
    throw new Error("Missing return statement in function");
}

//<VARDECL> := <E>
  static final public Absyn.Expr Expression() throws ParseException {Absyn.Expr e;
    e = OrExpr();
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr OrExpr() throws ParseException {Absyn.Expr e1,e2;
    e1 = AndExpr();
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 28:{
        ;
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        break label_14;
      }
      jj_consume_token(28);
      e2 = AndExpr();
e1 = new Absyn.OrExpr(e1,e2);
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr AndExpr() throws ParseException {Absyn.Expr e1,e2;
    e1 = EqualExpr();
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 27:{
        ;
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        break label_15;
      }
      jj_consume_token(27);
      e2 = EqualExpr();
e1 = new Absyn.AndExpr(e1,e2);
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr EqualExpr() throws ParseException {Absyn.Expr e1,e2;
    e1 = RelationalExpr();
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 29:
      case 56:{
        ;
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        break label_16;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 29:{
        jj_consume_token(29);
        e2 = RelationalExpr();
e1 = new Absyn.EqualExpr(e1,e2);
        break;
        }
      case 56:{
        jj_consume_token(56);
        e2 = RelationalExpr();
e1 = new Absyn.NotEqExpr(e1,e2);
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr RelationalExpr() throws ParseException {Absyn.Expr e1,e2;
    e1 = AdditiveExpr();
    label_17:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 30:
      case 31:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_17;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 30:{
        jj_consume_token(30);
        e2 = AdditiveExpr();
e1 = new Absyn.GreaterExpr(e1,e2);
        break;
        }
      case 31:{
        jj_consume_token(31);
        e2 = AdditiveExpr();
e1 = new Absyn.LesserExpr(e1,e2);
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

//<E>:= <MulE> + <MulE>
//   || <Mule> - <MulE>
  static final public Absyn.Expr AdditiveExpr() throws ParseException {Absyn.Expr e1,e2;
    e1 = MultiplicativeExpr();
    label_18:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 23:
      case 24:{
        ;
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        break label_18;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 23:{
        jj_consume_token(23);
        e2 = MultiplicativeExpr();
e1 = new Absyn.AddExpr(e1,e2);
        break;
        }
      case 24:{
        jj_consume_token(24);
        e2 = MultiplicativeExpr();
e1 = new Absyn.SubExpr(e1,e2);
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

//<MulE> := <Base> * <Base>
//       || <Base> / <Base>
  static final public Absyn.Expr MultiplicativeExpr() throws ParseException {Absyn.Expr e1,e2;
    e1 = UnaryExpr();
    label_19:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 25:
      case 26:{
        ;
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        break label_19;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 25:{
        jj_consume_token(25);
        e2 = UnaryExpr();
e1 = new Absyn.MulExpr(e1,e2);
        break;
        }
      case 26:{
        jj_consume_token(26);
        e2 = UnaryExpr();
e1 = new Absyn.DivExpr(e1,e2);
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr UnaryExpr() throws ParseException {Absyn.Expr e1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 24:{
      jj_consume_token(24);
      e1 = UnaryExpr();
e1 = new Absyn.NegExpr(e1);
      break;
      }
    case 32:{
      jj_consume_token(32);
      e1 = UnaryExpr();
e1 = new Absyn.NotExpr(e1);
      break;
      }
    case 11:
    case 12:
    case 13:
    case 14:
    case 35:
    case 44:
    case 45:
    case INT:
    case STRING:
    case ID:{
      e1 = PostfixExpr();
      break;
      }
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr PostfixExpr() throws ParseException {Absyn.Expr e1, arg;
 Token t;
 LinkedList<Absyn.Expr> args2;
    e1 = BaseExpr();
    label_20:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 21:
      case 37:{
        ;
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        break label_20;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 21:{
        jj_consume_token(21);
        t = jj_consume_token(ID);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 35:{
          jj_consume_token(35);
args2 = new LinkedList<Absyn.Expr>();
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 11:
          case 12:
          case 13:
          case 14:
          case 24:
          case 32:
          case 35:
          case 44:
          case 45:
          case INT:
          case STRING:
          case ID:{
            arg = Expression();
args2.add(arg);
            label_21:
            while (true) {
              switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
              case 40:{
                ;
                break;
                }
              default:
                jj_la1[33] = jj_gen;
                break label_21;
              }
              jj_consume_token(40);
              arg = Expression();
args2.add(arg);
            }
            break;
            }
          default:
            jj_la1[34] = jj_gen;
            ;
          }
          jj_consume_token(36);
e1 = new Absyn.CallExpr(e1, t.toString(), args2);
          break;
          }
        default:
          jj_la1[35] = jj_gen;
e1 = new Absyn.FieldExpr(e1, t.toString());
        }
        break;
        }
      case 37:{
        jj_consume_token(37);
        arg = Expression();
        jj_consume_token(38);
e1 = new Absyn.ArrayExpr(e1, arg);
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

//Base := <ID>
//     || <INT>
//     || <STRING>
//     || "true"
//     || "false"
//     || "this"
//     || "null"
  static final public Absyn.Expr BaseExpr() throws ParseException {Token t, name;
 Absyn.Expr e1, arg;
 Absyn.Type type2;
 LinkedList<Absyn.Expr> args3;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 45:{
      jj_consume_token(45);
      type2 = BaseType();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 35:{
        jj_consume_token(35);
        jj_consume_token(36);
{if ("" != null) return new Absyn.NewObjectExpr(type2);}
        break;
        }
      case 37:{
        jj_consume_token(37);
        arg = Expression();
        jj_consume_token(38);
args3 = new LinkedList<Absyn.Expr>(); args3.add(arg);
        label_22:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 37:{
            ;
            break;
            }
          default:
            jj_la1[37] = jj_gen;
            break label_22;
          }
          jj_consume_token(37);
          jj_consume_token(38);
args3.add(null);
        }
{if ("" != null) return new Absyn.NewArrayExpr(type2, args3);}
        break;
        }
      default:
        jj_la1[38] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    case 44:{
      jj_consume_token(44);
      jj_consume_token(21);
      name = jj_consume_token(ID);
      jj_consume_token(35);
args3 = new LinkedList<Absyn.Expr>();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 11:
      case 12:
      case 13:
      case 14:
      case 24:
      case 32:
      case 35:
      case 44:
      case 45:
      case INT:
      case STRING:
      case ID:{
        arg = Expression();
args3.add(arg);
        label_23:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 40:{
            ;
            break;
            }
          default:
            jj_la1[39] = jj_gen;
            break label_23;
          }
          jj_consume_token(40);
          arg = Expression();
args3.add(arg);
        }
        break;
        }
      default:
        jj_la1[40] = jj_gen;
        ;
      }
      jj_consume_token(36);
{if ("" != null) return new Absyn.XinuCallExpr(name.toString(), args3);}
      break;
      }
    case 35:{
      jj_consume_token(35);
      e1 = Expression();
      jj_consume_token(36);
{if ("" != null) return e1;}
      break;
      }
    case ID:{
      t = jj_consume_token(ID);
{if ("" != null) return new Absyn.IdentifierExpr(t.toString());}
      break;
      }
    case INT:{
      t = jj_consume_token(INT);
{if ("" != null) return new Absyn.IntegerLiteral(new Integer(t.toString()));}
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
{if ("" != null) return new Absyn.StringLiteral(t.toString());}
      break;
      }
    case 11:{
      t = jj_consume_token(11);
{if ("" != null) return new Absyn.TrueExpr();}
      break;
      }
    case 12:{
      t = jj_consume_token(12);
{if ("" != null) return new Absyn.FalseExpr();}
      break;
      }
    case 13:{
      t = jj_consume_token(13);
{if ("" != null) return new Absyn.ThisExpr();}
      break;
      }
    case 14:{
      t = jj_consume_token(14);
{if ("" != null) return new Absyn.NullExpr();}
      break;
      }
    default:
      jj_la1[41] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_3R_WhileCallStatement_379_2_62()
 {
    if (jj_scan_token(15)) return true;
    if (jj_scan_token(35)) return true;
    if (jj_3R_Expression_400_2_36()) return true;
    if (jj_scan_token(36)) return true;
    if (jj_3R_Statement_335_2_50()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_VarDeclaration_306_2_25()) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_553_11_94()
 {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  static private boolean jj_3R_IfCallStatement_368_4_71()
 {
    if (jj_scan_token(17)) return true;
    if (jj_3R_Statement_335_2_50()) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_557_5_98()
 {
    if (jj_scan_token(14)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_556_5_97()
 {
    if (jj_scan_token(13)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_555_5_96()
 {
    if (jj_scan_token(12)) return true;
    return false;
  }

  static private boolean jj_3R_IfCallStatement_367_2_63()
 {
    if (jj_scan_token(16)) return true;
    if (jj_scan_token(35)) return true;
    if (jj_3R_Expression_400_2_36()) return true;
    if (jj_scan_token(36)) return true;
    if (jj_3R_Statement_335_2_50()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_IfCallStatement_368_4_71()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_BaseExpr_554_5_95()
 {
    if (jj_scan_token(11)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_552_5_93()
 {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_551_5_92()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_550_5_91()
 {
    if (jj_scan_token(35)) return true;
    if (jj_3R_Expression_400_2_36()) return true;
    if (jj_scan_token(36)) return true;
    return false;
  }

  static private boolean jj_3R_BlockCallStatement_356_8_69()
 {
    if (jj_3R_Statement_335_2_50()) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_548_6_107()
 {
    if (jj_scan_token(40)) return true;
    if (jj_3R_Expression_400_2_36()) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_547_6_103()
 {
    if (jj_3R_Expression_400_2_36()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_BaseExpr_548_6_107()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_BaseExpr_545_5_90()
 {
    if (jj_scan_token(44)) return true;
    if (jj_scan_token(21)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(35)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_BaseExpr_547_6_103()) jj_scanpos = xsp;
    if (jj_scan_token(36)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_542_7_106()
 {
    if (jj_scan_token(37)) return true;
    if (jj_scan_token(38)) return true;
    return false;
  }

  static private boolean jj_3R_BlockCallStatement_356_2_60()
 {
    if (jj_scan_token(33)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_BlockCallStatement_356_8_69()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(34)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_540_6_102()
 {
    if (jj_scan_token(37)) return true;
    if (jj_3R_Expression_400_2_36()) return true;
    if (jj_scan_token(38)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_BaseExpr_542_7_106()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_BaseExpr_538_4_101()
 {
    if (jj_scan_token(35)) return true;
    if (jj_scan_token(36)) return true;
    return false;
  }

  static private boolean jj_3R_AssignCallStatement_347_2_64()
 {
    if (jj_3R_Expression_400_2_36()) return true;
    if (jj_scan_token(22)) return true;
    if (jj_3R_Expression_400_2_36()) return true;
    if (jj_scan_token(39)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_536_3_89()
 {
    if (jj_scan_token(45)) return true;
    if (jj_3R_BaseType_325_2_34()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_BaseExpr_538_4_101()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_540_6_102()) return true;
    }
    return false;
  }

  static private boolean jj_3R_BaseExpr_536_3_87()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_BaseExpr_536_3_89()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_545_5_90()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_550_5_91()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_551_5_92()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_552_5_93()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_553_11_94()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_554_5_95()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_555_5_96()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_556_5_97()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_557_5_98()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_ThreadDeclaration_225_3_24()) return true;
    return false;
  }

  static private boolean jj_3R_Statement_339_3_57()
 {
    if (jj_3R_AssignCallStatement_347_2_64()) return true;
    return false;
  }

  static private boolean jj_3R_Statement_338_3_56()
 {
    if (jj_3R_IfCallStatement_367_2_63()) return true;
    return false;
  }

  static private boolean jj_3R_Statement_337_3_55()
 {
    if (jj_3R_WhileCallStatement_379_2_62()) return true;
    return false;
  }

  static private boolean jj_3R_Statement_336_3_54()
 {
    if (jj_3R_XinuCallStatement_389_2_61()) return true;
    return false;
  }

  static private boolean jj_3R_Statement_335_2_50()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Statement_335_2_53()) {
    jj_scanpos = xsp;
    if (jj_3R_Statement_336_3_54()) {
    jj_scanpos = xsp;
    if (jj_3R_Statement_337_3_55()) {
    jj_scanpos = xsp;
    if (jj_3R_Statement_338_3_56()) {
    jj_scanpos = xsp;
    if (jj_3R_Statement_339_3_57()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_Statement_335_2_53()
 {
    if (jj_3R_BlockCallStatement_356_2_60()) return true;
    return false;
  }

  static private boolean jj_3R_VarDeclaration_306_30_30()
 {
    if (jj_scan_token(22)) return true;
    if (jj_3R_Expression_400_2_36()) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_327_4_40()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_326_4_39()
 {
    if (jj_scan_token(19)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpr_515_5_100()
 {
    if (jj_scan_token(37)) return true;
    if (jj_3R_Expression_400_2_36()) return true;
    if (jj_scan_token(38)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpr_513_6_105()
 {
    return false;
  }

  static private boolean jj_3R_PostfixExpr_511_7_109()
 {
    if (jj_scan_token(40)) return true;
    if (jj_3R_Expression_400_2_36()) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_325_2_38()
 {
    if (jj_scan_token(20)) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_325_2_34()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_BaseType_325_2_38()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseType_326_4_39()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseType_327_4_40()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_PostfixExpr_510_7_108()
 {
    if (jj_3R_Expression_400_2_36()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_PostfixExpr_511_7_109()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_PostfixExpr_509_4_104()
 {
    if (jj_scan_token(35)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PostfixExpr_510_7_108()) jj_scanpos = xsp;
    if (jj_scan_token(36)) return true;
    return false;
  }

  static private boolean jj_3R_Type_316_4_35()
 {
    if (jj_scan_token(37)) return true;
    if (jj_scan_token(38)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpr_507_3_99()
 {
    if (jj_scan_token(21)) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PostfixExpr_509_4_104()) {
    jj_scanpos = xsp;
    if (jj_3R_PostfixExpr_513_6_105()) return true;
    }
    return false;
  }

  static private boolean jj_3R_PostfixExpr_505_5_86()
 {
    if (jj_3R_BaseExpr_536_3_87()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_PostfixExpr_507_3_88()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_PostfixExpr_507_3_88()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PostfixExpr_507_3_99()) {
    jj_scanpos = xsp;
    if (jj_3R_PostfixExpr_515_5_100()) return true;
    }
    return false;
  }

  static private boolean jj_3R_Type_315_2_29()
 {
    if (jj_3R_BaseType_325_2_34()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Type_316_4_35()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_UnaryExpr_493_9_83()
 {
    if (jj_3R_PostfixExpr_505_5_86()) return true;
    return false;
  }

  static private boolean jj_3R_UnaryExpr_492_9_82()
 {
    if (jj_scan_token(32)) return true;
    if (jj_3R_UnaryExpr_490_5_77()) return true;
    return false;
  }

  static private boolean jj_3R_UnaryExpr_491_9_81()
 {
    if (jj_scan_token(24)) return true;
    if (jj_3R_UnaryExpr_490_5_77()) return true;
    return false;
  }

  static private boolean jj_3R_VarDeclaration_306_2_25()
 {
    if (jj_3R_Type_315_2_29()) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_VarDeclaration_306_30_30()) jj_scanpos = xsp;
    if (jj_scan_token(39)) return true;
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_3R_VarDeclaration_306_2_25()) return true;
    return false;
  }

  static private boolean jj_3R_UnaryExpr_490_5_77()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_UnaryExpr_491_9_81()) {
    jj_scanpos = xsp;
    if (jj_3R_UnaryExpr_492_9_82()) {
    jj_scanpos = xsp;
    if (jj_3R_UnaryExpr_493_9_83()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_VoidDeclaration_292_4_46()
 {
    if (jj_3R_Statement_335_2_50()) return true;
    return false;
  }

  static private boolean jj_3R_VoidDeclaration_290_4_45()
 {
    if (jj_3R_VarDeclaration_306_2_25()) return true;
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpr_481_3_85()
 {
    if (jj_scan_token(26)) return true;
    if (jj_3R_UnaryExpr_490_5_77()) return true;
    return false;
  }

  static private boolean jj_3R_VoidDeclaration_289_3_37()
 {
    if (jj_scan_token(9)) return true;
    if (jj_scan_token(18)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(35)) return true;
    if (jj_scan_token(36)) return true;
    if (jj_scan_token(33)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_VoidDeclaration_290_4_45()) { jj_scanpos = xsp; break; }
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_VoidDeclaration_292_4_46()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(34)) return true;
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpr_480_3_78()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_MultiplicativeExpr_480_3_84()) {
    jj_scanpos = xsp;
    if (jj_3R_MultiplicativeExpr_481_3_85()) return true;
    }
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpr_480_3_84()
 {
    if (jj_scan_token(25)) return true;
    if (jj_3R_UnaryExpr_490_5_77()) return true;
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpr_478_2_72()
 {
    if (jj_3R_UnaryExpr_490_5_77()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MultiplicativeExpr_480_3_78()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_3R_VarDeclaration_306_2_25()) return true;
    return false;
  }

  static private boolean jj_3R_FieldDeclaration_277_2_26()
 {
    if (jj_3R_Type_315_2_29()) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(39)) return true;
    return false;
  }

  static private boolean jj_3R_AdditiveExpr_467_3_80()
 {
    if (jj_scan_token(24)) return true;
    if (jj_3R_MultiplicativeExpr_478_2_72()) return true;
    return false;
  }

  static private boolean jj_3R_AdditiveExpr_466_3_73()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_AdditiveExpr_466_3_79()) {
    jj_scanpos = xsp;
    if (jj_3R_AdditiveExpr_467_3_80()) return true;
    }
    return false;
  }

  static private boolean jj_3R_AdditiveExpr_466_3_79()
 {
    if (jj_scan_token(23)) return true;
    if (jj_3R_MultiplicativeExpr_478_2_72()) return true;
    return false;
  }

  static private boolean jj_3R_AdditiveExpr_464_2_65()
 {
    if (jj_3R_MultiplicativeExpr_478_2_72()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AdditiveExpr_466_3_73()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_MethodDeclaration_264_7_43()
 {
    if (jj_3R_VarDeclaration_306_2_25()) return true;
    return false;
  }

  static private boolean jj_3R_MethodDeclaration_266_4_44()
 {
    if (jj_3R_Statement_335_2_50()) return true;
    return false;
  }

  static private boolean jj_3R_MethodDeclaration_255_12_31()
 {
    if (jj_scan_token(47)) return true;
    return false;
  }

  static private boolean jj_3R_MethodDeclaration_260_4_49()
 {
    if (jj_scan_token(40)) return true;
    if (jj_3R_Type_315_2_29()) return true;
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_RelationalExpr_452_3_75()
 {
    if (jj_scan_token(31)) return true;
    if (jj_3R_AdditiveExpr_464_2_65()) return true;
    return false;
  }

  static private boolean jj_3R_RelationalExpr_451_3_66()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_RelationalExpr_451_3_74()) {
    jj_scanpos = xsp;
    if (jj_3R_RelationalExpr_452_3_75()) return true;
    }
    return false;
  }

  static private boolean jj_3R_RelationalExpr_451_3_74()
 {
    if (jj_scan_token(30)) return true;
    if (jj_3R_AdditiveExpr_464_2_65()) return true;
    return false;
  }

  static private boolean jj_3R_MethodDeclaration_258_3_42()
 {
    if (jj_3R_Type_315_2_29()) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MethodDeclaration_260_4_49()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_RelationalExpr_449_2_58()
 {
    if (jj_3R_AdditiveExpr_464_2_65()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_RelationalExpr_451_3_66()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_MethodDeclaration_255_2_27()
 {
    if (jj_scan_token(9)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_MethodDeclaration_255_12_31()) jj_scanpos = xsp;
    if (jj_3R_Type_315_2_29()) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(35)) return true;
    xsp = jj_scanpos;
    if (jj_3R_MethodDeclaration_258_3_42()) jj_scanpos = xsp;
    if (jj_scan_token(36)) return true;
    if (jj_scan_token(33)) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MethodDeclaration_264_7_43()) { jj_scanpos = xsp; break; }
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MethodDeclaration_266_4_44()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(48)) return true;
    if (jj_3R_Expression_400_2_36()) return true;
    if (jj_scan_token(39)) return true;
    if (jj_scan_token(34)) return true;
    return false;
  }

  static private boolean jj_3R_EqualExpr_438_4_68()
 {
    if (jj_scan_token(56)) return true;
    if (jj_3R_RelationalExpr_449_2_58()) return true;
    return false;
  }

  static private boolean jj_3R_EqualExpr_437_3_59()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_EqualExpr_437_3_67()) {
    jj_scanpos = xsp;
    if (jj_3R_EqualExpr_438_4_68()) return true;
    }
    return false;
  }

  static private boolean jj_3R_EqualExpr_437_3_67()
 {
    if (jj_scan_token(29)) return true;
    if (jj_3R_RelationalExpr_449_2_58()) return true;
    return false;
  }

  static private boolean jj_3R_EqualExpr_435_2_51()
 {
    if (jj_3R_RelationalExpr_449_2_58()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_EqualExpr_437_3_59()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_3R_FieldDeclaration_277_2_26()) return true;
    return false;
  }

  static private boolean jj_3R_AndExpr_424_3_52()
 {
    if (jj_scan_token(27)) return true;
    if (jj_3R_EqualExpr_435_2_51()) return true;
    return false;
  }

  static private boolean jj_3R_ThreadDeclaration_231_3_33()
 {
    if (jj_3R_VoidDeclaration_289_3_37()) return true;
    return false;
  }

  static private boolean jj_3R_AndExpr_422_2_47()
 {
    if (jj_3R_EqualExpr_435_2_51()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AndExpr_424_3_52()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_3R_MethodDeclaration_255_2_27()) return true;
    return false;
  }

  static private boolean jj_3R_ThreadDeclaration_227_2_28()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_ThreadDeclaration_227_2_32()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_ThreadDeclaration_231_3_33()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_ThreadDeclaration_227_2_32()
 {
    if (jj_3R_FieldDeclaration_277_2_26()) return true;
    return false;
  }

  static private boolean jj_3R_ThreadDeclaration_225_3_24()
 {
    if (jj_scan_token(8)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(46)) return true;
    if (jj_scan_token(43)) return true;
    if (jj_scan_token(33)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_ThreadDeclaration_227_2_28()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(34)) return true;
    return false;
  }

  static private boolean jj_3R_OrExpr_411_3_48()
 {
    if (jj_scan_token(28)) return true;
    if (jj_3R_AndExpr_422_2_47()) return true;
    return false;
  }

  static private boolean jj_3R_OrExpr_409_2_41()
 {
    if (jj_3R_AndExpr_422_2_47()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_OrExpr_411_3_48()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Expression_400_2_36()
 {
    if (jj_3R_OrExpr_409_2_41()) return true;
    return false;
  }

  static private boolean jj_3R_XinuCallStatement_390_8_70()
 {
    if (jj_3R_Expression_400_2_36()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_XinuCallStatement_391_5_76()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_XinuCallStatement_391_5_76()
 {
    if (jj_scan_token(40)) return true;
    if (jj_3R_Expression_400_2_36()) return true;
    return false;
  }

  static private boolean jj_3R_XinuCallStatement_389_2_61()
 {
    if (jj_scan_token(44)) return true;
    if (jj_scan_token(21)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(35)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_XinuCallStatement_390_8_70()) jj_scanpos = xsp;
    if (jj_scan_token(36)) return true;
    if (jj_scan_token(39)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MiniJavaParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[42];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x100,0x100,0x101f800,0x0,0x180200,0x180200,0x180200,0x200,0x0,0x0,0x180000,0x101f800,0x101f800,0x400000,0x0,0x180000,0x101f800,0x101f800,0x20000,0x0,0x1007800,0x10000000,0x8000000,0x20000000,0x20000000,0xc0000000,0xc0000000,0x1800000,0x1800000,0x6000000,0x6000000,0x1007800,0x200000,0x0,0x1007800,0x0,0x200000,0x0,0x0,0x0,0x1007800,0x7800,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0xe300b,0x4000,0x80000,0x80000,0x80000,0x0,0x8000,0x100,0x80000,0xe300b,0xe300b,0x0,0x20,0x80000,0xe300b,0xe300b,0x0,0x100,0xe3009,0x0,0x0,0x1000000,0x1000000,0x0,0x0,0x0,0x0,0x0,0x0,0xe3009,0x20,0x100,0xe3009,0x8,0x20,0x20,0x28,0x100,0xe3009,0xe3008,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[6];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniJavaParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniJavaParser(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 42; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 42; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniJavaParser(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 42; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 42; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniJavaParser(MiniJavaParserTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 42; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniJavaParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 42; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[57];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 42; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 57; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 6; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

                               }
