/* MiniJavaParser.java */
/* Generated By:JavaCC: Do not edit this line. MiniJavaParser.java */
  package Parse;
  import java.util.LinkedList;
  public class MiniJavaParser implements MiniJavaParserConstants {

/********************/
/* MiniJava Grammar */
/********************/

// Goal 	::= 	MainClass ( ClassDeclaration | ThreadDeclaration )* <EOF>
  static final public Absyn.Program Goal() throws ParseException {LinkedList<Absyn.ClassDecl> cl = new LinkedList<Absyn.ClassDecl>();
    MainClassDeclaration(cl);
    jj_consume_token(0);
{if ("" != null) return new Absyn.Program(cl);}
    throw new Error("Missing return statement in function");
}

// MainClass 	::= 	"class" Identifier "{" "public" "static" "void" "main" "(" "String" "[" "]" Identifier ")" "{" Statement "}" "}"
  static final public Absyn.ClassDecl MainClassDeclaration(LinkedList<Absyn.ClassDecl> cl) throws ParseException {Absyn.ClassDecl  cd;
 Absyn.Stmt stmt;
 Absyn.VarDecl var;
 Token name, arg;
 LinkedList<Absyn.MethodDecl> methods = new LinkedList<Absyn.MethodDecl>();
 LinkedList<Absyn.Formal> formals     = new LinkedList<Absyn.Formal>();
 LinkedList<Absyn.VarDecl> locals     = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.Stmt> stmts         = new LinkedList<Absyn.Stmt>();
    jj_consume_token(6);
    name = jj_consume_token(ID);
    jj_consume_token(31);
    jj_consume_token(7);
    jj_consume_token(8);
    jj_consume_token(16);
    jj_consume_token(39);
    jj_consume_token(33);
    jj_consume_token(40);
    jj_consume_token(35);
    jj_consume_token(36);
    arg = jj_consume_token(ID);
    jj_consume_token(34);
formals.add(new Absyn.Formal(
   new Absyn.ArrayType(
    new Absyn.IdentifierType("String")),
     arg.toString()));
    jj_consume_token(31);
    label_1:
    while (true) {
      if (jj_2_1(2147483647)) {
        ;
      } else {
        break label_1;
      }
      var = VarDeclaration();
locals.add(var);
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 9:
      case 10:
      case 11:
      case 12:
      case 13:
      case 14:
      case 22:
      case 30:
      case 31:
      case 33:
      case 42:
      case 43:
      case INT:
      case STRING:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_2;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(32);
    jj_consume_token(32);
methods.add(new Absyn.MethodDecl(null, false, "main", formals,
    locals, stmts, new Absyn.IntegerLiteral(0)));
  cd = new Absyn.ClassDecl(name.toString(),
      null,
      new LinkedList<Absyn.VarDecl>(), methods);
  cl.add(cd);
  {if ("" != null) return cd;}
    throw new Error("Missing return statement in function");
}

/*
Absyn.Method MethodDeclaration() :
{
	Token arg;
	Absyn.Type type;	
}
{
	type = Type() arg = <ID> ";" {return ;}
}

Absyn.FieldDecl FieldDeclaration() :
{
	Token arg;
	Absyn.Type type;	
}
{
	type = Type() arg = <ID> ";" {return ;}
}
*/
// VarDeclaration 	::= 	Type Identifier ( = Expression )? ";"
  static final public Absyn.VarDecl VarDeclaration() throws ParseException {Absyn.Type type = null;
 Token      name = null;
 Absyn.Expr init = null;
    type = Type();
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 20:{
      jj_consume_token(20);
      init = Expression();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    jj_consume_token(37);
{if ("" != null) return new Absyn.VarDecl(type, name.toString(), init);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Type Type() throws ParseException {Absyn.Type type;
    type = BaseType();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 35:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_3;
      }
      jj_consume_token(35);
      jj_consume_token(36);
type = new Absyn.ArrayType(type);
    }
{if ("" != null) return type;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Type BaseType() throws ParseException {Token name;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 18:{
      name = jj_consume_token(18);
{if ("" != null) return new Absyn.BooleanType();}
      break;
      }
    case 17:{
      name = jj_consume_token(17);
{if ("" != null) return new Absyn.IntegerType();}
      break;
      }
    case ID:{
      name = jj_consume_token(ID);
{if ("" != null) return new Absyn.IdentifierType(name.toString());}
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Stmt Statement() throws ParseException {Absyn.Stmt stmt;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 31:{
      stmt = BlockCallStatement();
{if ("" != null) return stmt;}
      break;
      }
    case 42:{
      stmt = XinuCallStatement();
{if ("" != null) return stmt;}
      break;
      }
    case 13:{
      stmt = WhileCallStatement();
{if ("" != null) return stmt;}
      break;
      }
    case 14:{
      stmt = IfCallStatement();
{if ("" != null) return stmt;}
      break;
      }
    case 9:
    case 10:
    case 11:
    case 12:
    case 22:
    case 30:
    case 33:
    case 43:
    case INT:
    case STRING:
    case ID:{
      stmt = AssignCallStatement();
{if ("" != null) return stmt;}
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.AssignStmt AssignCallStatement() throws ParseException {Absyn.Expr arg1, arg2;
    arg1 = Expression();
    jj_consume_token(20);
    arg2 = Expression();
    jj_consume_token(37);
{if ("" != null) return new Absyn.AssignStmt((Absyn.AssignableExpr)arg1, arg2);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.BlockStmt BlockCallStatement() throws ParseException {Absyn.Stmt stmt;
 LinkedList<Absyn.Stmt> stmts = new LinkedList<Absyn.Stmt>();
    jj_consume_token(31);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 9:
      case 10:
      case 11:
      case 12:
      case 13:
      case 14:
      case 22:
      case 30:
      case 31:
      case 33:
      case 42:
      case 43:
      case INT:
      case STRING:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_4;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(32);
{if ("" != null) return new Absyn.BlockStmt(stmts);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.IfStmt IfCallStatement() throws ParseException {Absyn.Expr test;
 Absyn.Stmt thenStm;
 Absyn.Stmt elseStm = null;
    jj_consume_token(14);
    jj_consume_token(33);
    test = Expression();
    jj_consume_token(34);
    thenStm = Statement();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 15:{
      jj_consume_token(15);
      elseStm = Statement();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
{if ("" != null) return new Absyn.IfStmt(test, thenStm, elseStm);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.WhileStmt WhileCallStatement() throws ParseException {Absyn.Expr test;
 Absyn.Stmt body;
    jj_consume_token(13);
    jj_consume_token(33);
    test = Expression();
    jj_consume_token(34);
    body = Statement();
{if ("" != null) return new Absyn.WhileStmt(test, body);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.XinuCallStmt XinuCallStatement() throws ParseException {Token method;
 Absyn.Expr arg;
 LinkedList<Absyn.Expr> args = new LinkedList<Absyn.Expr>();
    jj_consume_token(42);
    jj_consume_token(19);
    method = jj_consume_token(ID);
    jj_consume_token(33);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 9:
    case 10:
    case 11:
    case 12:
    case 22:
    case 30:
    case 33:
    case 42:
    case 43:
    case INT:
    case STRING:
    case ID:{
      arg = Expression();
args.add(arg);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 38:{
          ;
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          break label_5;
        }
        jj_consume_token(38);
        arg = Expression();
args.add(arg);
      }
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    jj_consume_token(34);
    jj_consume_token(37);
{if ("" != null) return new Absyn.XinuCallStmt(method.toString(), args);}
    throw new Error("Missing return statement in function");
}

//<VARDECL> := <E>
  static final public Absyn.Expr Expression() throws ParseException {Absyn.Expr e;
    e = OrExpr();
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr OrExpr() throws ParseException {Absyn.Expr e1,e2;
    e1 = AndExpr();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 26:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_6;
      }
      jj_consume_token(26);
      e2 = AndExpr();
e1 = new Absyn.OrExpr(e1,e2);
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr AndExpr() throws ParseException {Absyn.Expr e1,e2;
    e1 = EqualExpr();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 25:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_7;
      }
      jj_consume_token(25);
      e2 = EqualExpr();
e1 = new Absyn.AndExpr(e1,e2);
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr EqualExpr() throws ParseException {Absyn.Expr e1,e2;
    e1 = RelationalExpr();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 27:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_8;
      }
      jj_consume_token(27);
      e2 = RelationalExpr();
e1 = new Absyn.EqualExpr(e1,e2);
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr RelationalExpr() throws ParseException {Absyn.Expr e1,e2;
    e1 = AdditiveExpr();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 28:
      case 29:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_9;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 28:{
        jj_consume_token(28);
        e2 = AdditiveExpr();
e1 = new Absyn.GreaterExpr(e1,e2);
        break;
        }
      case 29:{
        jj_consume_token(29);
        e2 = AdditiveExpr();
e1 = new Absyn.LesserExpr(e1,e2);
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

//<E>:= <MulE> + <MulE>
//   || <Mule> - <MulE>
  static final public Absyn.Expr AdditiveExpr() throws ParseException {Absyn.Expr e1,e2;
    e1 = MultiplicativeExpr();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 21:
      case 22:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_10;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 21:{
        jj_consume_token(21);
        e2 = MultiplicativeExpr();
e1 = new Absyn.AddExpr(e1,e2);
        break;
        }
      case 22:{
        jj_consume_token(22);
        e2 = MultiplicativeExpr();
e1 = new Absyn.SubExpr(e1,e2);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

//<MulE> := <Base> * <Base>
//       || <Base> / <Base>
  static final public Absyn.Expr MultiplicativeExpr() throws ParseException {Absyn.Expr e1,e2;
    e1 = UnaryExpr();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 23:
      case 24:{
        ;
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        break label_11;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 23:{
        jj_consume_token(23);
        e2 = UnaryExpr();
e1 = new Absyn.MulExpr(e1,e2);
        break;
        }
      case 24:{
        jj_consume_token(24);
        e2 = UnaryExpr();
e1 = new Absyn.DivExpr(e1,e2);
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr UnaryExpr() throws ParseException {Absyn.Expr e1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 22:{
      jj_consume_token(22);
      e1 = UnaryExpr();
e1 = new Absyn.NegExpr(e1);
      break;
      }
    case 30:{
      jj_consume_token(30);
      e1 = UnaryExpr();
e1 = new Absyn.NotExpr(e1);
      break;
      }
    case 9:
    case 10:
    case 11:
    case 12:
    case 33:
    case 42:
    case 43:
    case INT:
    case STRING:
    case ID:{
      e1 = PostfixExpr();
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr PostfixExpr() throws ParseException {Absyn.Expr e1, arg;
 Token t;
 LinkedList<Absyn.Expr> args2;
    e1 = BaseExpr();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 19:
      case 35:{
        ;
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 19:{
        jj_consume_token(19);
        t = jj_consume_token(ID);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 33:{
          jj_consume_token(33);
args2 = new LinkedList<Absyn.Expr>();
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 9:
          case 10:
          case 11:
          case 12:
          case 22:
          case 30:
          case 33:
          case 42:
          case 43:
          case INT:
          case STRING:
          case ID:{
            arg = Expression();
args2.add(arg);
            label_13:
            while (true) {
              switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
              case 38:{
                ;
                break;
                }
              default:
                jj_la1[20] = jj_gen;
                break label_13;
              }
              jj_consume_token(38);
              arg = Expression();
args2.add(arg);
            }
            break;
            }
          default:
            jj_la1[21] = jj_gen;
            ;
          }
          jj_consume_token(34);
e1 = new Absyn.CallExpr(e1, t.toString(), args2);
          break;
          }
        default:
          jj_la1[22] = jj_gen;
e1 = new Absyn.FieldExpr(e1, t.toString());
        }
        break;
        }
      case 35:{
        jj_consume_token(35);
        arg = Expression();
        jj_consume_token(36);
e1 = new Absyn.ArrayExpr(e1, arg);
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

//Base := <ID>
//     || <INT>
//     || <STRING>
//     || "true"
//     || "false"
//     || "this"
//     || "null"
  static final public Absyn.Expr BaseExpr() throws ParseException {Token t, name;
 Absyn.Expr e1, arg;
 Absyn.Type type2;
 LinkedList<Absyn.Expr> args3;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 43:{
      jj_consume_token(43);
      type2 = BaseType();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 33:{
        jj_consume_token(33);
        jj_consume_token(34);
{if ("" != null) return new Absyn.NewObjectExpr(type2);}
        break;
        }
      case 35:{
        jj_consume_token(35);
        arg = Expression();
        jj_consume_token(36);
args3 = new LinkedList<Absyn.Expr>(); args3.add(arg);
        label_14:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 35:{
            ;
            break;
            }
          default:
            jj_la1[24] = jj_gen;
            break label_14;
          }
          jj_consume_token(35);
          jj_consume_token(36);
args3.add(null);
        }
{if ("" != null) return new Absyn.NewArrayExpr(type2, args3);}
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    case 42:{
      jj_consume_token(42);
      jj_consume_token(19);
      name = jj_consume_token(ID);
      jj_consume_token(33);
args3 = new LinkedList<Absyn.Expr>();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 9:
      case 10:
      case 11:
      case 12:
      case 22:
      case 30:
      case 33:
      case 42:
      case 43:
      case INT:
      case STRING:
      case ID:{
        arg = Expression();
args3.add(arg);
        label_15:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 38:{
            ;
            break;
            }
          default:
            jj_la1[26] = jj_gen;
            break label_15;
          }
          jj_consume_token(38);
          arg = Expression();
args3.add(arg);
        }
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        ;
      }
      jj_consume_token(34);
{if ("" != null) return new Absyn.XinuCallExpr(name.toString(), args3);}
      break;
      }
    case 33:{
      jj_consume_token(33);
      e1 = Expression();
      jj_consume_token(34);
{if ("" != null) return e1;}
      break;
      }
    case ID:{
      t = jj_consume_token(ID);
{if ("" != null) return new Absyn.IdentifierExpr(t.toString());}
      break;
      }
    case INT:{
      t = jj_consume_token(INT);
{if ("" != null) return new Absyn.IntegerLiteral(new Integer(t.toString()));}
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
{if ("" != null) return new Absyn.StringLiteral(t.toString());}
      break;
      }
    case 9:{
      t = jj_consume_token(9);
{if ("" != null) return new Absyn.TrueExpr();}
      break;
      }
    case 10:{
      t = jj_consume_token(10);
{if ("" != null) return new Absyn.FalseExpr();}
      break;
      }
    case 11:{
      t = jj_consume_token(11);
{if ("" != null) return new Absyn.ThisExpr();}
      break;
      }
    case 12:{
      t = jj_consume_token(12);
{if ("" != null) return new Absyn.NullExpr();}
      break;
      }
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_3R_MultiplicativeExpr_370_3_46()
 {
    if (jj_scan_token(24)) return true;
    if (jj_3R_UnaryExpr_379_5_38()) return true;
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpr_369_3_39()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_MultiplicativeExpr_369_3_45()) {
    jj_scanpos = xsp;
    if (jj_3R_MultiplicativeExpr_370_3_46()) return true;
    }
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpr_369_3_45()
 {
    if (jj_scan_token(23)) return true;
    if (jj_3R_UnaryExpr_379_5_38()) return true;
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpr_367_2_34()
 {
    if (jj_3R_UnaryExpr_379_5_38()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MultiplicativeExpr_369_3_39()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_VarDeclaration_196_2_16()) return true;
    return false;
  }

  static private boolean jj_3R_AdditiveExpr_356_3_41()
 {
    if (jj_scan_token(22)) return true;
    if (jj_3R_MultiplicativeExpr_367_2_34()) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_442_11_55()
 {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  static private boolean jj_3R_AdditiveExpr_355_3_35()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_AdditiveExpr_355_3_40()) {
    jj_scanpos = xsp;
    if (jj_3R_AdditiveExpr_356_3_41()) return true;
    }
    return false;
  }

  static private boolean jj_3R_AdditiveExpr_355_3_40()
 {
    if (jj_scan_token(21)) return true;
    if (jj_3R_MultiplicativeExpr_367_2_34()) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_446_5_59()
 {
    if (jj_scan_token(12)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_445_5_58()
 {
    if (jj_scan_token(11)) return true;
    return false;
  }

  static private boolean jj_3R_AdditiveExpr_353_2_32()
 {
    if (jj_3R_MultiplicativeExpr_367_2_34()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AdditiveExpr_355_3_35()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_BaseExpr_444_5_57()
 {
    if (jj_scan_token(10)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_443_5_56()
 {
    if (jj_scan_token(9)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_441_5_54()
 {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_440_5_53()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_439_5_52()
 {
    if (jj_scan_token(33)) return true;
    if (jj_3R_Expression_290_2_21()) return true;
    if (jj_scan_token(34)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_437_6_68()
 {
    if (jj_scan_token(38)) return true;
    if (jj_3R_Expression_290_2_21()) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_436_6_64()
 {
    if (jj_3R_Expression_290_2_21()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_BaseExpr_437_6_68()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_BaseExpr_434_5_51()
 {
    if (jj_scan_token(42)) return true;
    if (jj_scan_token(19)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(33)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_BaseExpr_436_6_64()) jj_scanpos = xsp;
    if (jj_scan_token(34)) return true;
    return false;
  }

  static private boolean jj_3R_RelationalExpr_341_3_37()
 {
    if (jj_scan_token(29)) return true;
    if (jj_3R_AdditiveExpr_353_2_32()) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_431_7_67()
 {
    if (jj_scan_token(35)) return true;
    if (jj_scan_token(36)) return true;
    return false;
  }

  static private boolean jj_3R_RelationalExpr_340_3_33()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_RelationalExpr_340_3_36()) {
    jj_scanpos = xsp;
    if (jj_3R_RelationalExpr_341_3_37()) return true;
    }
    return false;
  }

  static private boolean jj_3R_RelationalExpr_340_3_36()
 {
    if (jj_scan_token(28)) return true;
    if (jj_3R_AdditiveExpr_353_2_32()) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_429_6_63()
 {
    if (jj_scan_token(35)) return true;
    if (jj_3R_Expression_290_2_21()) return true;
    if (jj_scan_token(36)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_BaseExpr_431_7_67()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_RelationalExpr_338_2_30()
 {
    if (jj_3R_AdditiveExpr_353_2_32()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_RelationalExpr_340_3_33()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_BaseExpr_427_4_62()
 {
    if (jj_scan_token(33)) return true;
    if (jj_scan_token(34)) return true;
    return false;
  }

  static private boolean jj_3R_BaseExpr_425_3_50()
 {
    if (jj_scan_token(43)) return true;
    if (jj_3R_BaseType_215_2_19()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_BaseExpr_427_4_62()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_429_6_63()) return true;
    }
    return false;
  }

  static private boolean jj_3R_BaseExpr_425_3_48()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_BaseExpr_425_3_50()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_434_5_51()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_439_5_52()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_440_5_53()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_441_5_54()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_442_11_55()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_443_5_56()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_444_5_57()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_445_5_58()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseExpr_446_5_59()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_EqualExpr_327_3_31()
 {
    if (jj_scan_token(27)) return true;
    if (jj_3R_RelationalExpr_338_2_30()) return true;
    return false;
  }

  static private boolean jj_3R_EqualExpr_325_2_28()
 {
    if (jj_3R_RelationalExpr_338_2_30()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_EqualExpr_327_3_31()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_VarDeclaration_196_30_18()
 {
    if (jj_scan_token(20)) return true;
    if (jj_3R_Expression_290_2_21()) return true;
    return false;
  }

  static private boolean jj_3R_AndExpr_314_3_29()
 {
    if (jj_scan_token(25)) return true;
    if (jj_3R_EqualExpr_325_2_28()) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_217_4_24()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_216_4_23()
 {
    if (jj_scan_token(17)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpr_404_5_61()
 {
    if (jj_scan_token(35)) return true;
    if (jj_3R_Expression_290_2_21()) return true;
    if (jj_scan_token(36)) return true;
    return false;
  }

  static private boolean jj_3R_AndExpr_312_2_26()
 {
    if (jj_3R_EqualExpr_325_2_28()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AndExpr_314_3_29()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_PostfixExpr_402_6_66()
 {
    return false;
  }

  static private boolean jj_3R_PostfixExpr_400_7_70()
 {
    if (jj_scan_token(38)) return true;
    if (jj_3R_Expression_290_2_21()) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_215_2_19()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_BaseType_215_2_22()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseType_216_4_23()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseType_217_4_24()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_BaseType_215_2_22()
 {
    if (jj_scan_token(18)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpr_399_7_69()
 {
    if (jj_3R_Expression_290_2_21()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_PostfixExpr_400_7_70()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_PostfixExpr_398_4_65()
 {
    if (jj_scan_token(33)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PostfixExpr_399_7_69()) jj_scanpos = xsp;
    if (jj_scan_token(34)) return true;
    return false;
  }

  static private boolean jj_3R_Type_206_4_20()
 {
    if (jj_scan_token(35)) return true;
    if (jj_scan_token(36)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpr_396_3_60()
 {
    if (jj_scan_token(19)) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PostfixExpr_398_4_65()) {
    jj_scanpos = xsp;
    if (jj_3R_PostfixExpr_402_6_66()) return true;
    }
    return false;
  }

  static private boolean jj_3R_OrExpr_301_3_27()
 {
    if (jj_scan_token(26)) return true;
    if (jj_3R_AndExpr_312_2_26()) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpr_394_5_47()
 {
    if (jj_3R_BaseExpr_425_3_48()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_PostfixExpr_396_3_49()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_PostfixExpr_396_3_49()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PostfixExpr_396_3_60()) {
    jj_scanpos = xsp;
    if (jj_3R_PostfixExpr_404_5_61()) return true;
    }
    return false;
  }

  static private boolean jj_3R_Type_205_2_17()
 {
    if (jj_3R_BaseType_215_2_19()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Type_206_4_20()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_OrExpr_299_2_25()
 {
    if (jj_3R_AndExpr_312_2_26()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_OrExpr_301_3_27()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_UnaryExpr_382_9_44()
 {
    if (jj_3R_PostfixExpr_394_5_47()) return true;
    return false;
  }

  static private boolean jj_3R_UnaryExpr_381_9_43()
 {
    if (jj_scan_token(30)) return true;
    if (jj_3R_UnaryExpr_379_5_38()) return true;
    return false;
  }

  static private boolean jj_3R_UnaryExpr_380_9_42()
 {
    if (jj_scan_token(22)) return true;
    if (jj_3R_UnaryExpr_379_5_38()) return true;
    return false;
  }

  static private boolean jj_3R_VarDeclaration_196_2_16()
 {
    if (jj_3R_Type_205_2_17()) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_VarDeclaration_196_30_18()) jj_scanpos = xsp;
    if (jj_scan_token(37)) return true;
    return false;
  }

  static private boolean jj_3R_Expression_290_2_21()
 {
    if (jj_3R_OrExpr_299_2_25()) return true;
    return false;
  }

  static private boolean jj_3R_UnaryExpr_379_5_38()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_UnaryExpr_380_9_42()) {
    jj_scanpos = xsp;
    if (jj_3R_UnaryExpr_381_9_43()) {
    jj_scanpos = xsp;
    if (jj_3R_UnaryExpr_382_9_44()) return true;
    }
    }
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MiniJavaParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[29];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0xc0407e00,0x100000,0x0,0x60000,0xc0407e00,0xc0407e00,0x8000,0x0,0x40401e00,0x4000000,0x2000000,0x8000000,0x30000000,0x30000000,0x600000,0x600000,0x1800000,0x1800000,0x40401e00,0x80000,0x0,0x40401e00,0x0,0x80000,0x0,0x0,0x0,0x40401e00,0x1e00,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x7c02,0x0,0x8,0x4000,0x7c02,0x7c02,0x0,0x40,0x7c02,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x7c02,0x8,0x40,0x7c02,0x2,0x8,0x8,0xa,0x40,0x7c02,0x7c02,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[1];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniJavaParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniJavaParser(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 29; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 29; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniJavaParser(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 29; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 29; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniJavaParser(MiniJavaParserTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 29; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniJavaParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 29; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[51];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 29; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 51; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 1; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

                               }
